#!/usr/bin/with-contenv bash

# set umask
UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

echo "[xTeVe] Waiting 11s for OpenVPN to boot before starting xTeVe" | ts '%Y-%m-%d %H:%M:%S'
sleep 11

echo "[xTeVe] Public IP: $(curl -s ifconfig.me)" | ts '%Y-%m-%d %H:%M:%S'
echo "[xTeVe] Start Script: xteve -port=${XTEVE_PORT} -config=/config -branch=${XTEVE_BRANCH} -debug=${XTEVE_DEBUG}" | ts '%Y-%m-%d %H:%M:%S'

exec \
    s6-setuidgid abc xteve \
    -port=${XTEVE_PORT} \
    -config=/config \
    -branch=${XTEVE_BRANCH} \
    -debug=${XTEVE_DEBUG}
