#!/usr/bin/with-contenv bash

# set umask
UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

sleep 10

echo "[xTeVe] Start Script: xteve -port=${XTEVE_PORT} -config=/config -branch=${XTEVE_BRANCH} -debug=${XTEVE_DEBUG}" | ts '%Y-%m-%d %H:%M:%S'

exec \
    s6-setuidgid abc xteve \
    -port=${XTEVE_PORT} \
    -config=/config \
    -branch=${XTEVE_BRANCH} \
    -debug=${XTEVE_DEBUG}
